"""
Generate a small labeled dataset of short sentences in different languages,
for training a language detection classifier.
"""

import pandas as pd
import random

random.seed(42)

samples = {
    "english": [
        "The weather is beautiful today.",
        "I would like to order a coffee please.",
        "She is reading a book in the library.",
        "We are going to the market tomorrow.",
        "He plays football every weekend.",
        "This restaurant serves great food.",
        "Can you help me with this problem?",
        "The children are playing in the park.",
        "I need to finish this report by Friday.",
        "Thank you very much for your help.",
        "The train arrives at nine o'clock.",
        "My favorite season is autumn.",
        "This movie was really interesting.",
        "Let's meet at the coffee shop.",
        "The store closes at ten tonight.",
        "I bought a new laptop yesterday.",
        "The sun rises early in summer.",
        "Please close the door quietly.",
        "We watched a documentary last night.",
        "The bridge connects two neighborhoods.",
        "She works as a nurse at the hospital.",
        "They traveled across the country by car.",
        "The garden is full of colorful flowers.",
        "He forgot his umbrella at the office.",
        "Our flight leaves early tomorrow morning.",
        "The bakery sells fresh bread every day.",
        "I usually walk to work in the morning.",
        "The museum has an interesting new exhibit.",
        "Please turn off the lights before leaving.",
        "The concert starts at eight in the evening.",
    ],
    "spanish": [
        "El clima esta hermoso hoy.",
        "Quisiera pedir un cafe por favor.",
        "Ella esta leyendo un libro en la biblioteca.",
        "Vamos al mercado manana.",
        "El juega futbol todos los fines de semana.",
        "Este restaurante sirve buena comida.",
        "Puedes ayudarme con este problema.",
        "Los ninos estan jugando en el parque.",
        "Necesito terminar este informe para el viernes.",
        "Muchas gracias por tu ayuda.",
        "El tren llega a las nueve.",
        "Mi estacion favorita es el otono.",
        "Esta pelicula fue muy interesante.",
        "Nos vemos en la cafeteria.",
        "La tienda cierra a las diez esta noche.",
        "Compre una laptop nueva ayer.",
        "El sol sale temprano en verano.",
        "Por favor cierra la puerta con cuidado.",
        "Vimos un documental anoche.",
        "El puente conecta dos barrios.",
        "Ella trabaja como enfermera en el hospital.",
        "Viajaron por el pais en coche.",
        "El jardin esta lleno de flores coloridas.",
        "El olvido su paraguas en la oficina.",
        "Nuestro vuelo sale temprano manana.",
        "La panaderia vende pan fresco todos los dias.",
        "Normalmente camino al trabajo por la manana.",
        "El museo tiene una nueva exposicion interesante.",
        "Por favor apaga las luces antes de salir.",
        "El concierto empieza a las ocho de la noche.",
    ],
    "french": [
        "Le temps est magnifique aujourd'hui.",
        "Je voudrais commander un cafe s'il vous plait.",
        "Elle lit un livre a la bibliotheque.",
        "Nous allons au marche demain.",
        "Il joue au football chaque week-end.",
        "Ce restaurant sert de la bonne nourriture.",
        "Pouvez-vous m'aider avec ce probleme?",
        "Les enfants jouent dans le parc.",
        "Je dois terminer ce rapport avant vendredi.",
        "Merci beaucoup pour votre aide.",
        "Le train arrive a neuf heures.",
        "Ma saison preferee est l'automne.",
        "Ce film etait vraiment interessant.",
        "Retrouvons-nous au café.",
        "Le magasin ferme a dix heures ce soir.",
        "J'ai achete un nouvel ordinateur hier.",
        "Le soleil se leve tot en ete.",
        "Veuillez fermer la porte doucement.",
        "Nous avons regarde un documentaire hier soir.",
        "Le pont relie deux quartiers.",
        "Elle travaille comme infirmiere a l'hopital.",
        "Ils ont voyage a travers le pays en voiture.",
        "Le jardin est plein de fleurs colorees.",
        "Il a oublie son parapluie au bureau.",
        "Notre vol part tot demain matin.",
        "La boulangerie vend du pain frais tous les jours.",
        "Je marche generalement au travail le matin.",
        "Le musee a une nouvelle exposition interessante.",
        "Veuillez eteindre les lumieres avant de partir.",
        "Le concert commence a huit heures du soir.",
    ],
    "german": [
        "Das Wetter ist heute wunderschoen.",
        "Ich haette gerne einen Kaffee bitte.",
        "Sie liest ein Buch in der Bibliothek.",
        "Wir gehen morgen zum Markt.",
        "Er spielt jedes Wochenende Fussball.",
        "Dieses Restaurant serviert gutes Essen.",
        "Koennen Sie mir bei diesem Problem helfen?",
        "Die Kinder spielen im Park.",
        "Ich muss diesen Bericht bis Freitag fertigstellen.",
        "Vielen Dank fuer Ihre Hilfe.",
        "Der Zug kommt um neun Uhr an.",
        "Meine Lieblingsjahreszeit ist der Herbst.",
        "Dieser Film war wirklich interessant.",
        "Treffen wir uns im Cafe.",
        "Das Geschaeft schliesst heute um zehn Uhr.",
        "Ich habe gestern einen neuen Laptop gekauft.",
        "Die Sonne geht im Sommer frueh auf.",
        "Bitte schliessen Sie die Tuer leise.",
        "Wir haben gestern Abend eine Dokumentation gesehen.",
        "Die Bruecke verbindet zwei Stadtteile.",
        "Sie arbeitet als Krankenschwester im Krankenhaus.",
        "Sie reisten mit dem Auto durch das Land.",
        "Der Garten ist voller bunter Blumen.",
        "Er hat seinen Regenschirm im Buero vergessen.",
        "Unser Flug geht morgen frueh.",
        "Die Baeckerei verkauft jeden Tag frisches Brot.",
        "Ich gehe normalerweise morgens zur Arbeit.",
        "Das Museum hat eine interessante neue Ausstellung.",
        "Bitte schalten Sie das Licht aus, bevor Sie gehen.",
        "Das Konzert beginnt um acht Uhr abends.",
    ],
    "italian": [
        "Il tempo e bellissimo oggi.",
        "Vorrei ordinare un caffe per favore.",
        "Lei sta leggendo un libro in biblioteca.",
        "Andiamo al mercato domani.",
        "Lui gioca a calcio ogni fine settimana.",
        "Questo ristorante serve ottimo cibo.",
        "Puoi aiutarmi con questo problema?",
        "I bambini stanno giocando nel parco.",
        "Devo finire questo rapporto entro venerdi.",
        "Grazie mille per il tuo aiuto.",
        "Il treno arriva alle nove.",
        "La mia stagione preferita e l'autunno.",
        "Questo film era davvero interessante.",
        "Incontriamoci al bar.",
        "Il negozio chiude alle dieci stasera.",
        "Ho comprato un nuovo computer ieri.",
        "Il sole sorge presto in estate.",
        "Per favore chiudi la porta piano.",
        "Abbiamo guardato un documentario ieri sera.",
        "Il ponte collega due quartieri.",
        "Lei lavora come infermiera in ospedale.",
        "Hanno viaggiato per il paese in auto.",
        "Il giardino e pieno di fiori colorati.",
        "Ha dimenticato l'ombrello in ufficio.",
        "Il nostro volo parte presto domani mattina.",
        "Il panificio vende pane fresco ogni giorno.",
        "Di solito cammino al lavoro la mattina.",
        "Il museo ha una nuova mostra interessante.",
        "Per favore spegni le luci prima di uscire.",
        "Il concerto inizia alle otto di sera.",
    ],
}


def generate_dataset():
    rows = []
    for language, sentences in samples.items():
        for sentence in sentences:
            rows.append({"text": sentence, "language": language})

    df = pd.DataFrame(rows).sample(frac=1, random_state=42).reset_index(drop=True)
    return df


if __name__ == "__main__":
    df = generate_dataset()
    df.to_csv("language_dataset.csv", index=False)
    print(f"Dataset created: language_dataset.csv ({len(df)} sentences)")
    print(df.head())
    print("\nLanguage distribution:")
    print(df["language"].value_counts())